baseurl = "http://www.irenakowal.com/"
languageCode = "en-us"
title = "Irene Kowal"
# Enable comments by entering your Disqus shortname
disqusShortname = "spf13"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-75344053-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:slug"


[params]
    # Tell me who you are
    author = "Irena Kowal"
    bio = "Author - Playwright"
    location = "Boston, MA"
    site_description = ""
    copyright  = "Powered by [Hugo](www.irenakowal.com)."
    avatar = "css/images/author-bio.jpg"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
#    follow_button = "https://github.com/digitalcraftsman"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "irene-kowal-7a460131"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "irena.kowal.14"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
